Zod discriminated union discriminator value accepts zod enum
colinhacks/zod pull request #1213
Opened 2022-06-19 22:05 UTC by tianhuil

Zod discriminated union discriminator value accepts zod enum:

```ts
const item = z
  .discriminatedUnion("type", [
    z.object({ type: z.literal("a"), a: z.string() }),
    z.object({ type: z.enum(["b", "c"]), b: z.string() }),
  ])
  .parse({ type: "b", b: "abc" });
```

Updates test, README.md documentation, and some minor changes from lint / prettier.

Requested in https://github.com/colinhacks/zod/issues/1075 and https://github.com/colinhacks/zod/issues/1015.

2022-06-22 00:22 UTC, tianhuil commented
@colinhacks -- any thoughts?

2022-10-05 01:20 UTC, scotttrinh requested changes

2022-10-05 01:20 UTC, scotttrinh commented on src/types.ts
> +        }
Do we need this runtime check and error here?

2022-10-05 01:20 UTC, scotttrinh commented on src/types.ts
> +export function deepPartialify<T extends ZodTypeAny>(
I think it would be a better to split off this update to `deepPartialify` since it's not necessary for the rest of the work here.

2022-11-25 10:54 UTC, maxArturo commented
Hello @tianhuil @scotttrinh ! I'm wondering if this is still being worked on? It seems that the PR's feature [already works](https://github.com/colinhacks/zod/issues/1075#issuecomment-1324937116). Just asking because I ran into this while implementing https://github.com/colinhacks/zod/pull/1589.

2023-04-24 14:52 UTC, tianhuil commented
@scotttrinh / @maxArturo: I'm happy to resubmit with just the changes concerning `deepPartialify()` to add union and discriminated union, if that is still of interest.  Sorry, I stopped paying attention once the issue became stale but happy to re-engage.

2023-08-23 18:40 UTC, closed without merging