add `.utc()`string format
colinhacks/zod pull request #1494
Opened 2022-10-15 05:51 UTC by samchungy

Adds `.utc()` from https://github.com/colinhacks/zod/issues/126

I've kinda done two versions. Happy to close one or the other if we can get a solution :) https://github.com/colinhacks/zod/pull/1489

2022-10-15 05:55 UTC, samchungy commented on src/types.ts
> +  | { kind: "utc"; options?: { milliseconds?: Boolean }; message?: string };
Went with an options object here for better visual clarity.

`.utc(true)`/`.utc(false)` did not read as well to me.

2022-10-19 22:05 UTC, colinhacks requested changes

2022-10-19 22:05 UTC, colinhacks commented on src/types.ts
> +        const isMsString = isDate && parsedDate.toISOString() === input.data;
Interesting approach but I think this is better implemented with regexes for the "ISO with ms" and "ISO without ms".

2022-10-19 22:06 UTC, colinhacks commented
This looks great, thanks! Any interest in adding the `.iso8601()` method to this PR too? 😛

2022-10-21 13:15 UTC, samchungy commented
> This looks great, thanks! Any interest in adding the `.iso8601()` method to this PR too (which allows offsets)? 😛
> 
> I like this PR more than the other.

Only because you asked nicely 😛

2022-10-28 21:21 UTC, samchungy commented
Question is - it looks like the regex I copy pasted supports an unlimited number of ms. Should we cap it at 3 or should we provide an option which allows someone to configure it. Eg. By default only accept 3 ms characters

2022-11-15 00:02 UTC, colinhacks approved these changes

2022-11-15 00:03 UTC, colinhacks commented
Sorry, after all this I had a change of heart and went a pretty different direction. Take a look and let me know if you have any thoughts.

2022-11-15 03:08 UTC, samchungy commented
> Sorry, after all this I had a change of heart and went a pretty different direction. I just pushed a couple commits to this PR to reflect my latest thinking on this API.
> 
> ```ts
> z.string().datetime();  // millis supported but optional, offsets not allowed
> z.string().datetime({ offset: true });  // millis supported but optional, offsets allowed
> z.string().datetime({ precision: 3 });  // millis required to 3 decimal places, offsets not allowed
> z.string().datetime({ precision: 0 });  // millis not allowed, offsets not allowed
> z.string().datetime({ precision: 3, offset: true });  // millis required to 3 decimal places, offsets allowed
> ```
> 
> The main driver of this approach is that the result of `new Date().toISOString()` should pass validation against `z.string().datetime()` out of the box, so millis should be supported without additional configuration.

Oooo I do like this approach. A few configs which are merged together like precision and offset. I like it. Let me know if you want me do anything :)

2022-11-15 06:04 UTC, merged

2022-11-15 06:05 UTC, colinhacks commented
Awesome. Thanks for your work on this Sam! Hard to believe it's been two years since I first wrote out that mini-RFC for `.utc()/.iso8601()` 🫠 Feels great to finally merge something here.

2022-11-24 09:46 UTC, devj3ns commented
Awesome addition to zod 😍

@colinhacks when will this feature be released on npm?

2022-12-08 10:31 UTC, mauriciabad commented
@colinhacks any news about the released on npm?

2022-12-12 07:44 UTC, samchungy commented
> @colinhacks any news about the release on npm?

If you're super keen jump on the beta [3.20.0-beta.0](https://www.npmjs.com/package/zod/v/3.20.0-beta.0). Release notes are [here](
https://github.com/colinhacks/zod/releases/tag/v3.20.0).

Otherwise, we wait! 😄 Please remember Colin is just a solo person working on this.

2022-12-12 10:23 UTC, samchungy commented
Nevermind it's officially in https://github.com/colinhacks/zod/releases/tag/v3.20 :)