Add forms context section
colinhacks/zod pull request #2467
Opened 2023-05-30 21:38 UTC by mikeybinns

Closes #2466

This PR adds a short explainer section to ensure people who are using Zod with forms have the correct context when working with forms and don't expect a "required string" Zod schema to prevent empty strings.

2023-06-02 15:28 UTC, scotttrinh requested changes
This is really great, thanks so much for doing this. Some minor edits requested.

2023-06-02 15:28 UTC, scotttrinh commented on README.md
> +Zod and HTML forms share some common terms, but they do not mean the same thing, which can lead to some confusion.
```suggestion
TypeScript and HTML forms share some common terms, but they do not mean the same thing, which can lead to some confusion when using Zod which uses terms consistent with TypeScript's usage.
```

2023-06-02 15:28 UTC, scotttrinh commented on README.md
> +One common misstep is that the schema `z.string()` will allow empty strings for a required HTML form field, which matches the typescript type system, but might not be what you expect.
```suggestion
One common misstep is that the schema `z.string()` will allow empty strings for a required HTML form field, which matches the TypeScript type system, but might not be what you expect when you consider the `z.string()` is "required" be default. However, "required" in this context means a value of this type is present and the empty string is a value of type `string`.
```

2023-06-02 15:28 UTC, scotttrinh commented on README.md
> +### Using Zod with forms
```suggestion

### Using Zod with forms
```

2023-06-02 15:28 UTC, scotttrinh commented on README.md
> +```
It's hard to use GitHub's suggestion feature on code blocks, but can you make the following changes:

1. Use ` ```ts`
2. The options you list below should also use ` ```ts` code fences in the examples.
3. Can you format the code examples like prettier with no configuration would? Our formatting is pretty inconsistent, but I'd like to improve that in general.

2023-09-03 11:58 UTC, mikeybinns commented
I have added all the suggested changed, just waiting for you to approve and merge :)

2024-02-08 15:53 UTC, mikeybinns commented
@scotttrinh Hi this is all ready and updated, I'm not sure why it says "Changes requested" still, but I've done all the requested changes and marked the conversations as resolved. Can we get this merged in?

2024-04-09 03:56 UTC, colinhacks commented
I appreciate the effort here, but I don't think something like this worth extending the already-very-long README.

2024-04-09 03:56 UTC, closed without merging