Handle singular and plural verbiage
colinhacks/zod pull request #784
Opened 2021-11-24 21:14 UTC by bsell93

Hello! Would love to handle singular/plural grammar in the error messages. Open to suggestions & other changes. I thought I'd at least put this out there to see if there are any thoughts on this.

2021-12-06 14:25 UTC, scotttrinh approved these changes
@bsell93 

Thanks for bringing this up! User facing copy is always such an 🙃 thing in error messaging, so improving that is always a welcome update. There is probably something more consistent that we can do, but I think what you have here is an improvement already, and Colin has stated that copy changes are not "breaking", so I think this is safe to merge. Thanks!

2021-12-06 14:34 UTC, scotttrinh commented on src/ZodError.ts
> +        } character${issue.minimum === 1 ? '' : 's'} long`;
```suggestion
        } character${issue.maximum === 1 ? '' : 's'} long`;
```

2021-12-08 18:26 UTC, scotttrinh requested changes

2021-12-08 18:26 UTC, scotttrinh commented on src/ZodError.ts
> +        } character${issue.minimum === 1 ? '' : 's'} long`;
did you mean to add ` long` here? If so, we'll need to update the failing test.

2021-12-30 05:08 UTC, colinhacks commented
Thanks for this PR @bsell93. It motivated me to go a slightly different direction with these error messages that I think is more explicit: https://github.com/colinhacks/zod/commit/2021a5e07c3e0a06a33b4c44441fc9863ae51ae4 

Closing for now.

2021-12-30 05:08 UTC, closed without merging

2021-12-30 11:50 UTC, bsell93 commented
Glad to bring inspiration! 😁